version: '3'
services:
  postgres:
    image: postgres:11-alpine
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - ALLOW_IP_RANGE=0.0.0.0/0
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata: